config/routes.rb
# -*- encoding : utf-8 -*-
Sms::Application.routes.draw do

  #ADMIN ZONE
  scope :admin do
    #/admin/users
    get 'users' => 'admin/users#index'
    resource :user, only: [] do
      get 'new' => 'admin/user#new', as: :new
      post 'new' => 'admin/user#create', as: :create

      get ':id' => 'admin/user#show', as: :show
      post ':id' => 'admin/user#update', as: :update
    end
    #/admin/users

    #/admin/tariffs
    resource :tariffs, only: [] do
      get ':id' => 'admin/tariffs#index', as: :index
      post ':id/create' => 'admin/tariffs#create', as: :create
      get ':id/new' => 'admin/tariffs#new', as: :new
      delete ':id/delete' => 'admin/tariffs#destroy', as: :delete
    end
    #/admin/tariffs

    #/admin/payments
    resource :payments, only: [] do
      get ':id' => 'admin/payments#index', as: :index
      post ':id/create' => 'admin/payments#create', as: :create
      get ':id/new' => 'admin/payments#new', as: :new
      delete ':id/delete' => 'admin/payments#destroy', as: :delete

      post ':id/approve' => 'admin/payments#approve', as: :approve
      post ':id/refuse' => 'admin/payments#refuse', as: :refuse
    end
    #/admin/payments

  end

  namespace :admin do

    #/admin/report
    namespace :report do
      match 'charges', via: [:get, :post]
      match 'payments', via: [:get, :post]
    end
    get 'report/charges/xls' => 'report#charges_xls'
    #/admin/report

    #/admin/operators
    get 'operators' => 'operators#index', as: :operators_index
    #/admin/operators

    #/admin/operator_tariffs
    get 'operator/:operator_id/tariffs' => 'operator_tariff#index', as: :operator_tariffs
    get 'operator/:operator_id/tariff/new' => 'operator_tariff#new', as: :operator_tariff_new
    post 'operator/:operator_id/tariff/create' => 'operator_tariff#create', as: :operator_tariff_create

    post 'operator/tariff/:operator_tariff_id/update' => 'operator_tariff#update', as: :operator_tariff_update
    get 'operator/tariff/:operator_tariff_id/edit' => 'operator_tariff#edit', as: :operator_tariff_edit
    delete 'operator/tariff/:operator_tariff_id' => 'operator_tariff#destroy', as: :operator_tariff_destroy
    #/admin/operator_tariffs

    #/admin/sender_names
    get 'sender_names' => 'sender_names#index'
    get 'sender_names/:id/accept' => 'sender_names#accept', as: :sender_name_accept
    get 'sender_names/:id/reject' => 'sender_names#reject', as: :sender_name_reject
    #/admin/sender_names

    #/admin/black_lists
    get 'black_lists' => 'black_lists#index'
    get 'black_lists/new'
    post 'black_lists' => 'black_lists#create', as: :black_lists_create
    delete 'black_lists/:id' => 'black_lists#destroy', as: :black_lists_delete
    #/admin/black_lists
  end
  #ADMIN ZONE

  #USER ZONE
  #/api
  namespace :api do
    get 'send', action: :send_sms
    get 'report', action: :report_sms
  end
  #/api

  #/api/faq
  get 'api/faq' => 'api_faq#index'
  #/api/faq

  #/sms
  get 'sms' => 'sms#index'
  #/sms

  #/send_sms
  match 'send_sms' => 'sms#send_sms', via: [:get, :post]
  #/send_sms

  #/message/sms_count
  match 'message/sms_count' => 'message#sms_count', via: :all
  #/message/sms_count

  #/message_price/calc
  match 'message_price/calc' => 'message_price#calc', via: :all
  #/message_price/calc

  #/autodelivery
  resource :autodelivery, only: [] do
    get '/' => 'autodelivery#index'
    get 'new' => 'autodelivery#new', as: :new
    get ':id' => 'autodelivery#show', as: :show
    post '/' => 'autodelivery#create', as: :create
    delete ':id' => 'autodelivery#destroy', as: :delete
    post ':id' => 'autodelivery#update', as: :update

    member do
      get ':id/activate' => 'autodelivery#activate', as: :activate
      get ':id/deactivate' => 'autodelivery#deactivate', as: :deactivate
      get ':id/run' => 'autodelivery#run', as: :run
    end
  end
  #/autodelivery

  #/groups
  get 'groups' => 'groups#index'
  #/groups

  #/group
  resource :group, only: [] do
    get 'new' => 'group#new', as: :new
    get ':id' => 'group#show', as: :show
    post '/' => 'group#create', as: :create
    delete ':id' => 'group#destroy', as: :delete
    post ':id' => 'group#update', as: :update

    member do
      get ':id/upload' => 'group#show_upload', as: :show_upload
      post ':id/upload' => 'group#upload', as: :upload
      post ':id/birthday_congratulation' => 'group#birthday_congratulation', as: :birthday_congratulation
    end
  end
  #/group

  #/client
  resource :client, only: [] do
    get 'new' => 'client#new', as: :new
    get ':id' => 'client#show', as: :show
    post '/' => 'client#create', as: :create
    delete ':id' => 'client#destroy', as: :delete
    post ':id' => 'client#update', as: :update

    member do
      post ':id/birthday_congratulation' => 'client#birthday_congratulation_update', as: :birthday_congratulation
    end
  end
  #/client

  #/sender_names
  get 'sender_names' => 'sender_names#index'

  resource :sender_name, only: [] do
    get 'new' => 'sender_name#new', as: :new
    post '/' => 'sender_name#create', as: :create
    delete ':id' => 'sender_name#destroy', as: :delete

    member do
      get ':id/use' => 'sender_name#use', as: :use
    end
  end
  #/sender_names

  #/change_password
  get 'change_password' => 'password#new', as: :new_password
  post 'change_password' => 'password#update', as: :update_password
  #/change_password

  #/login, /logout
  devise_for :users, :path => "/", :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:sessions => "sessions"}
  #/login, /logout

  #/tariffs
  get 'tariffs' => 'tariffs#index'
  #/tariffs

  #/contact
  get 'contact' => 'contact#show', as: :show_contact
  post 'contact' => 'contact#update', as: :update_contact
  #/contact

  #/night_delivery
  get 'night_delivery' => 'night_delivery#show', as: :show_night_delivery
  post 'night_delivery' => 'night_delivery#update', as: :update_night_delivery
  #/night_delivery

  #/templates
  get 'templates' => 'templates#index'

  resource :template, only: [] do
    get 'new' => 'template#new', as: :new
    post '/' => 'template#create', as: :create
    delete ':id' => 'template#destroy', as: :delete
    get ':id' => 'template#show', as: :show
    post ':id' => 'template#update', as: :update
  end
  #/templates

  #/template_birthday
  resource :template_birthday, only: [] do
    get '/' => 'template_birthday#show', as: :show
    post '/' => 'template_birthday#update', as: :update
  end
  #/template_birthday

  #/blacklist
  resource :blacklist, only: [] do
    get 'new' => 'blacklist#new', as: :new
    post '/' => 'blacklist#create', as: :create
    delete ':id' => 'blacklist#destroy', as: :delete
    get '/' => 'blacklist#show', as: :show
  end
  #/blacklist

  #/report_by_date
  get 'report_by_date' => 'report_by_date#show', as: :show_report_by_date
  post 'report_by_date' => 'report_by_date#generate', as: :generate_report_by_date
  #/report_by_date

  #/logs
  get 'logs' => 'logs#index'

  resource :log, only: [] do
    member do
      get ':id' => 'log#show', as: :show
      get ':id/stop' => 'log#stop', as: :stop
      get ':id/report' => 'log#report', as: :report
      get ':id/delete_clients' => 'log#delete_clients', as: :delete_clients
      get ':id/new_delivery' => 'log#new_delivery', as: :new_delivery
    end
  end
  #/logs

  #root
  root to: 'welcome#index'
  #root

  #USER ZONE
end

app/models/sender_name.rb
# -*- encoding : utf-8 -*-
class SenderName < ActiveRecord::Base

  belongs_to :user

  attr_accessible :value, :user_id, :status_id, :active

  belongs_to :status, :class_name => 'SenderNameStatus'

  include Service::SenderName::Status
  include Service::SenderName::Moderating
  include Service::SenderName::Activator
  include Service::SenderName::Notificator

  validates :value, :presence => true

  def self.active_sender_name_value(user)
    _sender_names = self.where(:user_id => user.id, :active => true, :status_id => SenderNameStatus.accepted.id).order('created_at ASC')

    if _sender_names.count == 1 and self.verified?(_sender_names.first.value, user)
      return _sender_names.first.value
    end

    if _sender_names.count > 1 and self.verified?(_sender_names.last.value, user)
      return _sender_names.last.value
    end

    nil
  end

  def self.verified?(sender_name_value, user)
    return true if def?(sender_name_value) and user.permit_def_sender_name?
    return true if alpha?(sender_name_value) and user.permit_alpha_sender_name?

    false
  end

  def self.valid_by_value?(sender_name_value, user)
    if verified?(sender_name_value, user)
      if user.accepted_sender_name_values.map { |v| v[:value].to_s }.include? sender_name_value.to_s
        return true
      end
    end

    false
  end

  def self.def?(sender_name_value)
    #для DEF
    #длина = 11 символов
    #должен начинаться только 79

    return true if sender_name_value.to_s.length == 11 and sender_name_value.to_s.scan(/^79\d{9}*$/).join.present?
    false
  end

  def self.alpha?(sender_name_value)
    #ALPHA
    #длина <= 11 символов, не может быть DEF
    #исключаем также все номера на 78, 88, 89
    #могут быть буквы, цифры, символы: - , + , _ , пробел , символ точки

    if sender_name_value.to_s.length == 11
      return false if sender_name_value.to_s.scan(/^78\d{9}*$/).join.present?
      return false if sender_name_value.to_s.scan(/^88\d{9}*$/).join.present?
      return false if sender_name_value.to_s.scan(/^89\d{9}*$/).join.present?
    end

    if not def?(sender_name_value) and sender_name_value.to_s.length <= 11 and sender_name_value.to_s.scan(/^[a-zA-Z\-\_\+\.\d\s]*$/).join.present?
      return true
    end

    false
  end
end

app/models/service/sender_name/activator.rb
# -*- encoding : utf-8 -*-
module Service::SenderName::Activator
  def activate
    if self.accepted?
      deactivate_active(self.user)

      #активируем выбранный sender_name
      self.update_attribute(:active, true)

      return true
    end

    false
  end

  def deactivate_active(user)
    #деактивируем текущий активный sender_name
    SenderName.where(:user_id => user, :active => true).map { |sender_name| sender_name.update_attribute(:active, false) }
  end
end

app/models/service/sender_name/moderating.rb
# -*- encoding : utf-8 -*-
module Service::SenderName::Moderating

  def accept
    if accepted? or moderating?
      self.update_attribute(:status, SenderNameStatus.accepted)
    else
      self.reject
    end
  end

  def reject
    self.update_attribute(:status, SenderNameStatus.rejected)
  end

end

app/models/service/sender_name/notificator.rb
# -*- encoding : utf-8 -*-
module Service::SenderName::Notificator

  def self.included(base)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def create_with_notify(user, new_value)
      if SenderName.verified?(new_value, user)
        sender_name = SenderName.create!(value: new_value, user_id: user.id, status_id: SenderNameStatus.moderating.id)
        Admin.delay.notify(:event => I18n.t('sender_name.admin_notify.created') % [user.email, new_value])

        return sender_name
      end
    end
  end

  def update_with_notify(new_value)
    self.update_attribute(:value, new_value)

    if SenderName.verified?(new_value, self.user)
      self.update_attribute(:status, SenderNameStatus.moderating)

      Admin.delay.notify(:event => I18n.t('sender_name.admin_notify.updated') % [self.user.email, new_value])

      return true
    else
      self.update_attribute(:status, SenderNameStatus.rejected)
    end

    false
  end

end

app/models/service/sender_name/status.rb
# -*- encoding : utf-8 -*-
module Service::SenderName::Status
  def status
    if not SenderName.verified?(value, self.user)
      return SenderNameStatus.rejected
    end

    super
  end

  def accepted?
    status.internal_name.to_s == SenderNameStatus.accepted.internal_name.to_s
  end

  def rejected?
    status.internal_name.to_s == SenderNameStatus.rejected.internal_name.to_s
  end

  def moderating?
    status.internal_name.to_s == SenderNameStatus.moderating.internal_name.to_s
  end
end

app/models/service/users/sender_name.rb
# -*- encoding : utf-8 -*-
require 'sender_name.rb'
module Service::Users::SenderName
  def active_sender_name_value
    SenderName.active_sender_name_value(self)
  end

  def accepted_sender_name_values
    sender_names.select { |sender_name| sender_name.accepted? }
  end
end

app/controllers/admin/sender_names_controller.rb
# -*- encoding : utf-8 -*-
class Admin::SenderNamesController < Admin::ApplicationController
  before_filter :find_sender_name!, :only => [:accept, :reject]

  def index
    @sender_names = SenderName.where(:status_id => SenderNameStatus.moderating)
  end

  def accept
    @sender_name.accept
    flash[:notice] = 'Имя отправителя одобрено'
    redirect_to admin_sender_names_path
  end

  def reject
    @sender_name.reject
    flash[:notice] = 'Имя отправителя отклонено'

    redirect_to admin_sender_names_path
  end

  private
  def find_sender_name!
    id = sanitize_params[:id]

    @sender_name = SenderName.find_by_id(id)
    if not @sender_name
      flash[:alert] = I18n.t('sender_name.not_exist') % id
      redirect_to admin_sender_names_path
    end
  end

  def sanitize_params
    params.permit(:id)
  end

end

app/controllers/sender_name_controller.rb
# -*- encoding : utf-8 -*-
class SenderNameController < AuthController
  before_filter :find_sender_name!, only: [:use, :destroy]
  before_filter :check_exist_sender_name!, only: [:create]

  def create
    sender_name = SenderName.create_with_notify(current_user, sanitize_params[:value])

    if sender_name
      flash[:notice] = I18n.t('sender_name.create_success')
    else
      flash[:alert] = I18n.t('sender_name.verified_failed')
    end

    redirect_to sender_names_path
  end

  def destroy
    @sender_name.destroy
    flash[:notice] = I18n.t('sender_name.delete_success')

    redirect_to sender_names_path
  end

  def use
    if @sender_name.activate
      flash[:notice] = I18n.t('sender_name.activate_success')
    else
      if @sender_name.rejected?
        flash[:alert] = I18n.t('sender_name.verified_failed')
      else
        flash[:alert] = I18n.t('sender_name.on_moderating')
      end
    end

    redirect_to sender_names_path
  end

  private
  def find_sender_name!
    id = sanitize_params[:id]

    @sender_name = SenderName.find_by_id_and_user_id(id, current_user.id)

    if not @sender_name
      flash[:alert] = I18n.t('sender_name.not_exist') % id
      redirect_to sender_names_path
    end
  end

  def sanitize_params
    params.permit(:id, :value)
  end

  def check_exist_sender_name!
    _value = sanitize_params[:value]

    _sender_name = SenderName.find_by_value_and_user_id(_value, current_user.id)
    if _sender_name
      flash[:alert] = I18n.t('sender_name.already_exist') % _value
      redirect_to sender_names_path
    end
  end

end

app/controllers/sender_names_controller.rb
# -*- encoding : utf-8 -*-
class SenderNamesController < AuthController

  def index
    @sender_names = current_user.sender_names.order(:value)
  end

end

app/views/sender_names/_panel.html.erb
<div class="row">
  <div class="twelve columns">
    <div class="panel">
      <p>После редактирования имена отправителей проходят ручную проверку. Будьте терпеливы.</p>

      <% if current_user.permit_alpha_sender_name? and current_user.permit_def_sender_name? %>
          <p>
            <strong>
              Ограничения: только английские буквы и/или цифры, а также символы "-", "+", "_", " ", ".". Длина - до 11
              символов
              включительно. Русские символы не поддерживаются.
              <br>
              Если это федеральный номер(длина = 11 символов) - то он должен начинаться только с 79.
              <br>
              Пример корректных имён: 79379903835, BRW-Mebel, Ruslan, ANGELALUX.
              <br>
              Пример некорретных имён: 89379903835, Вася, 88462241023, 8(937)990-38-35, Одежда из Белоруссии.
            </strong>
          </p>
      <% end %>

      <% if not current_user.permit_alpha_sender_name? and current_user.permit_def_sender_name? %>
          <p>
            <strong>
              Ограничения: только телефонный номер в федеральном формате. Длина - строго 11
              символов. Должен начинаться только с 79.
              <br>
              Пример корректных имён: 79379903835.
              <br>
              Пример некорретных имён: 89379903835, BRW-Mebel, Ruslan, ANGELALUX, Вася, 88462241023, 8(937)990-38-35,
              Одежда из Белоруссии.
            </strong>
          </p>
      <% end %>

      <% if current_user.permit_alpha_sender_name? and not current_user.permit_def_sender_name? %>
          <p>
            <strong>
              Ограничения: только английские буквы и/или цифры, а также символы "-", "+", "_", " ", ".". Длина - до 11
              символов
              включительно. Русские символы не поддерживаются. Номера в федеральном формате не поддерживаются.
              <br>
              <br>
              Пример корректных имён: BRW-Mebel, Ruslan, ANGELALUX.
              <br>
              Пример некорретных имён: 79379903835, 89379903835, Вася, 88462241023, 8(937)990-38-35, Одежда из Белоруссии.
            </strong>
          </p>
      <% end %>

      <% if not current_user.permit_alpha_sender_name? and not current_user.permit_def_sender_name? %>
          <p>
            <strong>
              Для вас не активирована рассылка ни через один канал.
              Просьба связаться со службой техподдержки. Любые имена отправителя не пройдут проверку.
            </strong>
          </p>
      <% end %>

    </div>
  </div>
</div>

app/views/sender_names/index.html.erb
<%= render 'panel' %>

<div class="row">
  <div class="twelve columns">
    <%= link_to 'Добавить имя отправителя', new_sender_name_path, class: :button %>
  </div>
</div>

<br>

<div class="row">
  <div class="twelve columns">
    <table class="twelve">
      <thead>
      <tr>
        <th>Имя отправителя</th>
        <th>Статус</th>
        <th>Действия</th>
      </tr>
      </thead>
      <tbody>

      <% @sender_names.each do |sender_name| %>
          <tr>
            <td><%= sender_name.value %></td>

            <td>
              <% if not SenderName.verified?(sender_name.value, current_user) %>
                <span class="alert label">
                <%= sender_name.status.name %>
              <% else %>
                  <% if sender_name.active? %>
                    <span class="label">Используется по умолчанию
                  <% else %>
                      <% if sender_name.accepted? %>
                        <span class="success label">
                        <%= sender_name.status.name %>
                      <% end %>

                      <% if sender_name.moderating? %>
                        <span class="secondary label">
                        <%= sender_name.status.name %>
                      <% end %>

                      <% if sender_name.rejected? %>
                        <span class="alert label">
                        <%= sender_name.status.name %>
                      <% end %>
                  <% end %>
              <% end %>
              </span>
            </td>

            <td>
              <% if not sender_name.active? and sender_name.accepted? %>
                  <%= link_to 'Использовать по умолчанию', use_sender_name_path(sender_name) %>
                  |
              <% else %>
                  <%= link_to 'Использовать по умолчанию', '#', style: 'visibility: hidden;' %>
              <% end %>

              <%= link_to 'Удалить', delete_sender_name_path(sender_name), method: :delete, data: {confirm: "Вы уверены что хотите удалить имя отправителя?"} %>
            </td>
          </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>